#!/bin/sh

clear
if [ "$(id -u)" != "0" ]; then
	echo "Does not have ROOT privilege"
	exit
else
	echo "Have ROOT privilege"
fi

rm -f /home/devntnghia/.tmp_file
echo "------------------------------
WARNING! THIS COMMAND FILE WILL MAKE ABOUT 3 TEMP FILES!
PLEASE DO NOT DELETE THEM!
------------------------------"
if [ -f "/home/devntnghia/.default_user" ]; then
	default=$(cat /home/devntnghia/.default_user)
	echo "Default Username is $default"
else
	echo -n "Enter default Username (it will save for all session)
If you want to change this later, navigate to where the file default_user was saved and delete it.
> "
	read user
	echo "Default Username is: $user"
	echo -n "$user" >> /home/devntnghia/.default_user
	default=$(cat /home/devntnghia/.default_user)
fi

echo -n "Enter the Github Repository link that you want to clone without .git at the end
> "
read repo

echo "echo 'CLONING...'
git clone https://github.com/$default/$repo.git -q" >> /home/devntnghia/.tmp_file
echo "sudo rm -rf /home/devntnghia/$repo
sudo rm -rf /home/devntnghia/Desktop/$repo" >> /home/devntnghia/.delete_if_exist
cd /home/devntnghia
chmod 777 .delete_if_exist
chown devntnghia .delete_if_exist
./.delete_if_exist && rm -f .delete_if_exist
chown devntnghia .tmp_file
chmod 777 .tmp_file
./.tmp_file && rm -f .tmp_file
echo "DONE!"
mv -f /home/devntnghia/$repo /home/devntnghia/Desktop
chown -R devntnghia /home/devntnghia/Desktop/$repo
echo "Your cloned repo should be /home/devntnghia/Desktop/$repo"
